### PR TITLE
Fix validators page

### LINKED ISSUE #78: Mock Validators
Child of: #24 

As long as we don't have data from the block-chain, all possible view elements should be viewable so we can start testing early with users.

For the validators it shows an empty list for. We should mock this.

### PR DESCRIPTION
**Pull request by mappum**
Resolves #78

### CODE REVIEW

File: app/src/renderer/vuex/modules/validators.js [hunk 1]
```diff
@@ -10,18 +11,29 @@ export default ({ commit, node }) => {
     },
     setValidators (state, validators) {
       state.validators = validators
+      console.log('vallies', validators)
```
Comment (faboweb) [inline app/src/renderer/vuex/modules/validators.js]: should this stay in?

Comment (mappum) [reply app/src/renderer/vuex/modules/validators.js]: Oops, nope.
