### PR TITLE
Matt/158 - Show error for baseserver init failure

### LINKED ISSUE #158: No error shown if baseserver fails
There is no error shown in the UI if the baseserver fails.

- [ ] show error in UI if baseserver fails

image

### PR DESCRIPTION
**Pull request by mappum**
Closes #158 

In the case that baseserver fails to start up (rare, but has happened occasionally when the data directory was corrupted), we now show an error notification which stays present in the window. It could look better, but I'm not expecting this to happen much in the wild.

### CODE REVIEW

File: app/src/renderer/vuex/modules/node.js [hunk 1]
```diff
@@ -74,11 +74,19 @@ export default function ({ node }) {
       dispatch('pollRPCConnection')
     },
     async checkConnection ({ commit }) {
+      let error = () => commit('notifyError', {
+        title: 'Critical Error',
+        body: `Couldn't initialize the blockchain client. If the problem persists, please contact Cosmos support.`
```
Comment (jolesbi) [inline app/src/renderer/vuex/modules/node.js]: "If the problem persists, please make a ticket on <a>Github</a>"
